require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-i18n

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

I18n/RailsI18n:
  Enabled: true
I18n/GetText:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments
